Clean up

diff --git a/brainbash b/brainbash
--- a/brainbash
+++ b/brainbash
@@ -2,7 +2,7 @@
 
 die()
 {
-	printf '\e[31merror:\e[m %s\n' "$@" >&2
+	printf 'error: %s\n' "$@" >&2
 	exit 1
 }
 
@@ -10,7 +10,7 @@ if (( $# )); then
 	if [[ -e $1 ]]; then
 		program=$(< "$1")
 	else
-		die "file $1 does not exist"
+		die "file '$1' does not exist"
 	fi
 else
 	mapfile -t
