Clean up

diff --git a/brainbash b/brainbash
--- a/brainbash
+++ b/brainbash
@@ -2,7 +2,7 @@
 
 die()
 {
-	printf '\e[31merror:\e[m %s\n' "$@" >&2
+	printf '\e[31merror:\e[m %s\n' "$*" >&2
 	exit 1
 }
 
@@ -64,7 +64,10 @@ for (( ptr = 0; index < ${#program}; index++ )); do
 							(( depth-- ))
 							;;
 						'')
-							die "unmatched opening bracket"
+							die \
+								"unmatched" \
+								"opening" \
+								"bracket"
 							;;
 					esac
 				done
